SELECT 
    tahun,
    LTRIM(RTRIM(TA.nik)) AS nik,
    LTRIM(RTRIM(TK.NAMA)) AS nama,
    LTRIM(RTRIM(TD.[Nama Departemen])) AS nama_departemen,
    LTRIM(RTRIM(TB.[Nama Bagian])) AS nama_bagian,
    LTRIM(RTRIM(TJ.Jabatan)) AS jabatan,
    LTRIM(RTRIM(TK.[Tgl. Kerja Lama])) AS tgl_kerja_lama,
    LTRIM(RTRIM(TK.[Resign Date])) AS resign_date,
    
	SUM(
			CASE WHEN Sts01 = 'A' THEN 1 ELSE 0 END + CASE WHEN Sts02 = 'A' THEN 1 ELSE 0 END + CASE WHEN Sts03 = 'A' THEN 1 ELSE 0 END + CASE WHEN Sts04 = 'A' THEN 1 ELSE 0 END +
			CASE WHEN Sts05 = 'A' THEN 1 ELSE 0 END + CASE WHEN Sts06 = 'A' THEN 1 ELSE 0 END + CASE WHEN Sts07 = 'A' THEN 1 ELSE 0 END + CASE WHEN Sts08 = 'A' THEN 1 ELSE 0 END +
			CASE WHEN Sts09 = 'A' THEN 1 ELSE 0 END + CASE WHEN Sts10 = 'A' THEN 1 ELSE 0 END + CASE WHEN Sts11 = 'A' THEN 1 ELSE 0 END + CASE WHEN Sts12 = 'A' THEN 1 ELSE 0 END +
			CASE WHEN Sts13 = 'A' THEN 1 ELSE 0 END + CASE WHEN Sts14 = 'A' THEN 1 ELSE 0 END + CASE WHEN Sts15 = 'A' THEN 1 ELSE 0 END + CASE WHEN Sts16 = 'A' THEN 1 ELSE 0 END +
			CASE WHEN Sts17 = 'A' THEN 1 ELSE 0 END + CASE WHEN Sts18 = 'A' THEN 1 ELSE 0 END + CASE WHEN Sts19 = 'A' THEN 1 ELSE 0 END + CASE WHEN Sts20 = 'A' THEN 1 ELSE 0 END +
			CASE WHEN Sts21 = 'A' THEN 1 ELSE 0 END + CASE WHEN Sts22 = 'A' THEN 1 ELSE 0 END + CASE WHEN Sts23 = 'A' THEN 1 ELSE 0 END + CASE WHEN Sts24 = 'A' THEN 1 ELSE 0 END +
			CASE WHEN Sts25 = 'A' THEN 1 ELSE 0 END + CASE WHEN Sts26 = 'A' THEN 1 ELSE 0 END + CASE WHEN Sts27 = 'A' THEN 1 ELSE 0 END + CASE WHEN Sts28 = 'A' THEN 1 ELSE 0 END +
			CASE WHEN Sts29 = 'A' THEN 1 ELSE 0 END + CASE WHEN Sts30 = 'A' THEN 1 ELSE 0 END + CASE WHEN Sts31 = 'A' THEN 1 ELSE 0 END
		 )  AS ALFA,
    SUM(
			CASE WHEN Sts01 = 'I' THEN 1 ELSE 0 END + CASE WHEN Sts02 = 'I' THEN 1 ELSE 0 END + CASE WHEN Sts03 = 'I' THEN 1 ELSE 0 END + CASE WHEN Sts04 = 'I' THEN 1 ELSE 0 END +
			CASE WHEN Sts05 = 'I' THEN 1 ELSE 0 END + CASE WHEN Sts06 = 'I' THEN 1 ELSE 0 END + CASE WHEN Sts07 = 'I' THEN 1 ELSE 0 END + CASE WHEN Sts08 = 'I' THEN 1 ELSE 0 END +
			CASE WHEN Sts09 = 'I' THEN 1 ELSE 0 END + CASE WHEN Sts10 = 'I' THEN 1 ELSE 0 END + CASE WHEN Sts11 = 'I' THEN 1 ELSE 0 END + CASE WHEN Sts12 = 'I' THEN 1 ELSE 0 END +
			CASE WHEN Sts13 = 'I' THEN 1 ELSE 0 END + CASE WHEN Sts14 = 'I' THEN 1 ELSE 0 END + CASE WHEN Sts15 = 'I' THEN 1 ELSE 0 END + CASE WHEN Sts16 = 'I' THEN 1 ELSE 0 END +
			CASE WHEN Sts17 = 'I' THEN 1 ELSE 0 END + CASE WHEN Sts18 = 'I' THEN 1 ELSE 0 END + CASE WHEN Sts19 = 'I' THEN 1 ELSE 0 END + CASE WHEN Sts20 = 'I' THEN 1 ELSE 0 END +
			CASE WHEN Sts21 = 'I' THEN 1 ELSE 0 END + CASE WHEN Sts22 = 'I' THEN 1 ELSE 0 END + CASE WHEN Sts23 = 'I' THEN 1 ELSE 0 END + CASE WHEN Sts24 = 'I' THEN 1 ELSE 0 END +
			CASE WHEN Sts25 = 'I' THEN 1 ELSE 0 END + CASE WHEN Sts26 = 'I' THEN 1 ELSE 0 END + CASE WHEN Sts27 = 'I' THEN 1 ELSE 0 END + CASE WHEN Sts28 = 'I' THEN 1 ELSE 0 END +
			CASE WHEN Sts29 = 'I' THEN 1 ELSE 0 END + CASE WHEN Sts30 = 'I' THEN 1 ELSE 0 END + CASE WHEN Sts31 = 'I' THEN 1 ELSE 0 END
		 ) AS IZIN,
    
    SUM(
			CASE WHEN Sts01 = 'C' THEN 1 ELSE 0 END + CASE WHEN Sts02 = 'C' THEN 1 ELSE 0 END + CASE WHEN Sts03 = 'C' THEN 1 ELSE 0 END + CASE WHEN Sts04 = 'C' THEN 1 ELSE 0 END +
			CASE WHEN Sts05 = 'C' THEN 1 ELSE 0 END + CASE WHEN Sts06 = 'C' THEN 1 ELSE 0 END + CASE WHEN Sts07 = 'C' THEN 1 ELSE 0 END + CASE WHEN Sts08 = 'C' THEN 1 ELSE 0 END +
			CASE WHEN Sts09 = 'C' THEN 1 ELSE 0 END + CASE WHEN Sts10 = 'C' THEN 1 ELSE 0 END + CASE WHEN Sts11 = 'C' THEN 1 ELSE 0 END + CASE WHEN Sts12 = 'C' THEN 1 ELSE 0 END +
			CASE WHEN Sts13 = 'C' THEN 1 ELSE 0 END + CASE WHEN Sts14 = 'C' THEN 1 ELSE 0 END + CASE WHEN Sts15 = 'C' THEN 1 ELSE 0 END + CASE WHEN Sts16 = 'C' THEN 1 ELSE 0 END +
			CASE WHEN Sts17 = 'C' THEN 1 ELSE 0 END + CASE WHEN Sts18 = 'C' THEN 1 ELSE 0 END + CASE WHEN Sts19 = 'C' THEN 1 ELSE 0 END + CASE WHEN Sts20 = 'C' THEN 1 ELSE 0 END +
			CASE WHEN Sts21 = 'C' THEN 1 ELSE 0 END + CASE WHEN Sts22 = 'C' THEN 1 ELSE 0 END + CASE WHEN Sts23 = 'C' THEN 1 ELSE 0 END + CASE WHEN Sts24 = 'C' THEN 1 ELSE 0 END +
			CASE WHEN Sts25 = 'C' THEN 1 ELSE 0 END + CASE WHEN Sts26 = 'C' THEN 1 ELSE 0 END + CASE WHEN Sts27 = 'C' THEN 1 ELSE 0 END + CASE WHEN Sts28 = 'C' THEN 1 ELSE 0 END +
			CASE WHEN Sts29 = 'C' THEN 1 ELSE 0 END + CASE WHEN Sts30 = 'C' THEN 1 ELSE 0 END + CASE WHEN Sts31 = 'C' THEN 1 ELSE 0 END
			) AS CUTI_TAHUNAN,

	SUM(
			CASE WHEN Sts01 IN ('Y','V','W','X') THEN 1 ELSE 0 END + CASE WHEN Sts02 IN ('Y','V','W','X') THEN 1 ELSE 0 END + CASE WHEN Sts03 IN ('Y','V','W','X') THEN 1 ELSE 0 END + CASE WHEN Sts04 IN ('Y','V','W','X') THEN 1 ELSE 0 END +
			CASE WHEN Sts05 IN ('Y','V','W','X') THEN 1 ELSE 0 END + CASE WHEN Sts06 IN ('Y','V','W','X') THEN 1 ELSE 0 END + CASE WHEN Sts07 IN ('Y','V','W','X') THEN 1 ELSE 0 END + CASE WHEN Sts08 IN ('Y','V','W','X') THEN 1 ELSE 0 END +
			CASE WHEN Sts09 IN ('Y','V','W','X') THEN 1 ELSE 0 END + CASE WHEN Sts10 IN ('Y','V','W','X') THEN 1 ELSE 0 END + CASE WHEN Sts11 IN ('Y','V','W','X') THEN 1 ELSE 0 END + CASE WHEN Sts12 IN ('Y','V','W','X') THEN 1 ELSE 0 END +
			CASE WHEN Sts13 IN ('Y','V','W','X') THEN 1 ELSE 0 END + CASE WHEN Sts14 IN ('Y','V','W','X') THEN 1 ELSE 0 END + CASE WHEN Sts15 IN ('Y','V','W','X') THEN 1 ELSE 0 END + CASE WHEN Sts16 IN ('Y','V','W','X') THEN 1 ELSE 0 END +
			CASE WHEN Sts17 IN ('Y','V','W','X') THEN 1 ELSE 0 END + CASE WHEN Sts18 IN ('Y','V','W','X') THEN 1 ELSE 0 END + CASE WHEN Sts19 IN ('Y','V','W','X') THEN 1 ELSE 0 END + CASE WHEN Sts20 IN ('Y','V','W','X') THEN 1 ELSE 0 END +
			CASE WHEN Sts21 IN ('Y','V','W','X') THEN 1 ELSE 0 END + CASE WHEN Sts22 IN ('Y','V','W','X') THEN 1 ELSE 0 END + CASE WHEN Sts23 IN ('Y','V','W','X') THEN 1 ELSE 0 END + CASE WHEN Sts24 IN ('Y','V','W','X') THEN 1 ELSE 0 END +
			CASE WHEN Sts25 IN ('Y','V','W','X') THEN 1 ELSE 0 END + CASE WHEN Sts26 IN ('Y','V','W','X') THEN 1 ELSE 0 END + CASE WHEN Sts27 IN ('Y','V','W','X') THEN 1 ELSE 0 END + CASE WHEN Sts28 IN ('Y','V','W','X') THEN 1 ELSE 0 END +
			CASE WHEN Sts29 IN ('Y','V','W','X') THEN 1 ELSE 0 END + CASE WHEN Sts30 IN ('Y','V','W','X') THEN 1 ELSE 0 END + CASE WHEN Sts31 IN ('Y','V','W','X') THEN 1 ELSE 0 END
			) AS CUTI_LAINNYA ,

	SUM(
			CASE WHEN Sts01 = 'U' THEN 1 ELSE 0 END + CASE WHEN Sts02 = 'U' THEN 1 ELSE 0 END + CASE WHEN Sts03 = 'U' THEN 1 ELSE 0 END + CASE WHEN Sts04 = 'U' THEN 1 ELSE 0 END +
			CASE WHEN Sts05 = 'U' THEN 1 ELSE 0 END + CASE WHEN Sts06 = 'U' THEN 1 ELSE 0 END + CASE WHEN Sts07 = 'U' THEN 1 ELSE 0 END + CASE WHEN Sts08 = 'U' THEN 1 ELSE 0 END +
			CASE WHEN Sts09 = 'U' THEN 1 ELSE 0 END + CASE WHEN Sts10 = 'U' THEN 1 ELSE 0 END + CASE WHEN Sts11 = 'U' THEN 1 ELSE 0 END + CASE WHEN Sts12 = 'U' THEN 1 ELSE 0 END +
			CASE WHEN Sts13 = 'U' THEN 1 ELSE 0 END + CASE WHEN Sts14 = 'U' THEN 1 ELSE 0 END + CASE WHEN Sts15 = 'U' THEN 1 ELSE 0 END + CASE WHEN Sts16 = 'U' THEN 1 ELSE 0 END +
			CASE WHEN Sts17 = 'U' THEN 1 ELSE 0 END + CASE WHEN Sts18 = 'U' THEN 1 ELSE 0 END + CASE WHEN Sts19 = 'U' THEN 1 ELSE 0 END + CASE WHEN Sts20 = 'U' THEN 1 ELSE 0 END +
			CASE WHEN Sts21 = 'U' THEN 1 ELSE 0 END + CASE WHEN Sts22 = 'U' THEN 1 ELSE 0 END + CASE WHEN Sts23 = 'U' THEN 1 ELSE 0 END + CASE WHEN Sts24 = 'U' THEN 1 ELSE 0 END +
			CASE WHEN Sts25 = 'U' THEN 1 ELSE 0 END + CASE WHEN Sts26 = 'U' THEN 1 ELSE 0 END + CASE WHEN Sts27 = 'U' THEN 1 ELSE 0 END + CASE WHEN Sts28 = 'U' THEN 1 ELSE 0 END +
			CASE WHEN Sts29 = 'U' THEN 1 ELSE 0 END + CASE WHEN Sts30 = 'U' THEN 1 ELSE 0 END + CASE WHEN Sts31 = 'U' THEN 1 ELSE 0 END
			) AS CUTI_MELAHIRKAN ,

	SUM (
    CASE 
        WHEN TA.BULAN = '01' AND
            (
                CASE WHEN Sts01 = 'S' THEN 1 ELSE 0 END + 
                CASE WHEN Sts02 = 'S' THEN 1 ELSE 0 END + 
                CASE WHEN Sts03 = 'S' THEN 1 ELSE 0 END + 
                CASE WHEN Sts04 = 'S' THEN 1 ELSE 0 END +
                CASE WHEN Sts05 = 'S' THEN 1 ELSE 0 END + 
                CASE WHEN Sts06 = 'S' THEN 1 ELSE 0 END + 
                CASE WHEN Sts07 = 'S' THEN 1 ELSE 0 END + 
                CASE WHEN Sts08 = 'S' THEN 1 ELSE 0 END +
                CASE WHEN Sts09 = 'S' THEN 1 ELSE 0 END + 
                CASE WHEN Sts10 = 'S' THEN 1 ELSE 0 END + 
                CASE WHEN Sts11 = 'S' THEN 1 ELSE 0 END + 
                CASE WHEN Sts12 = 'S' THEN 1 ELSE 0 END +
                CASE WHEN Sts13 = 'S' THEN 1 ELSE 0 END + 
                CASE WHEN Sts14 = 'S' THEN 1 ELSE 0 END + 
                CASE WHEN Sts15 = 'S' THEN 1 ELSE 0 END + 
                CASE WHEN Sts16 = 'S' THEN 1 ELSE 0 END +
                CASE WHEN Sts17 = 'S' THEN 1 ELSE 0 END + 
                CASE WHEN Sts18 = 'S' THEN 1 ELSE 0 END + 
                CASE WHEN Sts19 = 'S' THEN 1 ELSE 0 END + 
                CASE WHEN Sts20 = 'S' THEN 1 ELSE 0 END +
                CASE WHEN Sts21 = 'S' THEN 1 ELSE 0 END + 
                CASE WHEN Sts22 = 'S' THEN 1 ELSE 0 END + 
                CASE WHEN Sts23 = 'S' THEN 1 ELSE 0 END + 
                CASE WHEN Sts24 = 'S' THEN 1 ELSE 0 END +
                CASE WHEN Sts25 = 'S' THEN 1 ELSE 0 END + 
                CASE WHEN Sts26 = 'S' THEN 1 ELSE 0 END + 
                CASE WHEN Sts27 = 'S' THEN 1 ELSE 0 END + 
                CASE WHEN Sts28 = 'S' THEN 1 ELSE 0 END +
                CASE WHEN Sts29 = 'S' THEN 1 ELSE 0 END + 
                CASE WHEN Sts30 = 'S' THEN 1 ELSE 0 END + 
                CASE WHEN Sts31 = 'S' THEN 1 ELSE 0 END
            ) > 0
        THEN 1 
        ELSE 0 
    END
) AS SAKIT_TANPA_SURATDOKTER,

	SUM(
			CASE WHEN Sts01 = 'D' THEN 1 ELSE 0 END + CASE WHEN Sts02 = 'D' THEN 1 ELSE 0 END + CASE WHEN Sts03 = 'D' THEN 1 ELSE 0 END + CASE WHEN Sts04 = 'D' THEN 1 ELSE 0 END +
			CASE WHEN Sts05 = 'D' THEN 1 ELSE 0 END + CASE WHEN Sts06 = 'D' THEN 1 ELSE 0 END + CASE WHEN Sts07 = 'D' THEN 1 ELSE 0 END + CASE WHEN Sts08 = 'D' THEN 1 ELSE 0 END +
			CASE WHEN Sts09 = 'D' THEN 1 ELSE 0 END + CASE WHEN Sts10 = 'D' THEN 1 ELSE 0 END + CASE WHEN Sts11 = 'D' THEN 1 ELSE 0 END + CASE WHEN Sts12 = 'D' THEN 1 ELSE 0 END +
			CASE WHEN Sts13 = 'D' THEN 1 ELSE 0 END + CASE WHEN Sts14 = 'D' THEN 1 ELSE 0 END + CASE WHEN Sts15 = 'D' THEN 1 ELSE 0 END + CASE WHEN Sts16 = 'D' THEN 1 ELSE 0 END +
			CASE WHEN Sts17 = 'D' THEN 1 ELSE 0 END + CASE WHEN Sts18 = 'D' THEN 1 ELSE 0 END + CASE WHEN Sts19 = 'D' THEN 1 ELSE 0 END + CASE WHEN Sts20 = 'D' THEN 1 ELSE 0 END +
			CASE WHEN Sts21 = 'D' THEN 1 ELSE 0 END + CASE WHEN Sts22 = 'D' THEN 1 ELSE 0 END + CASE WHEN Sts23 = 'D' THEN 1 ELSE 0 END + CASE WHEN Sts24 = 'D' THEN 1 ELSE 0 END +
			CASE WHEN Sts25 = 'D' THEN 1 ELSE 0 END + CASE WHEN Sts26 = 'D' THEN 1 ELSE 0 END + CASE WHEN Sts27 = 'D' THEN 1 ELSE 0 END + CASE WHEN Sts28 = 'D' THEN 1 ELSE 0 END +
			CASE WHEN Sts29 = 'D' THEN 1 ELSE 0 END + CASE WHEN Sts30 = 'D' THEN 1 ELSE 0 END + CASE WHEN Sts31 = 'D' THEN 1 ELSE 0 END
			) AS SAKIT_SURATDOKTER
    
FROM tblAttendance AS TA
INNER JOIN tblkaryawan AS TK WITH(NOLOCK) ON TA.nik=TK.nik
INNER JOIN tbldept AS TD WITH(NOLOCK) ON TD.[Kode Dept] =TK.[Kode Dept]
INNER JOIN TblJabatan AS TJ WITH(NOLOCK)  ON TJ.JabatanID = TK.[Kode Posisi]
INNER JOIN tblbagian AS TB WITH(NOLOCK) ON (TB.[Kode Dept] = TK.[Kode Dept] and TB.[Kode Bagian] =TK.[Kode Bagian] )
WHERE tahun = 2024 AND TA.NIK = 'K211109ASS0614'
GROUP BY tahun, TA.nik, TK.NAMA, TD.[Nama Departemen],TB.[Nama Bagian],TJ.Jabatan,[Tgl. Kerja Lama],[Resign Date]
ORDER BY NIK,NAMA

