select * from tblchek


INSERT INTO [dbo].[tblchek] (NIK, TAHUN, bulan, edt, edt1, edt2, edt3, edt4, edt5, edt6, edt7)
SELECT TCK.nik, TCK.TAHUN, TCK.BULAN, TCK.EDT, TCK.EDT1, TCK.EDT2, TCK.EDT3, TCK.EDT4, TCK.EDT5, TCK.EDT6, TCK.EDT7
FROM [dbo].[tblchek0] AS TCK

-------------------------------------------------

select * from TmpRpttblKaryawan

INSERT INTO [dbo].[tblSchedKontrak]
SELECT *
FROM [dbo].[tblSchedKontrak01]

INSERT INTO [dbo].[T_LG202308] (SRVDT,DEVDT,DEVUID,PKTDEVID,DEVLGIDX,USRID,USRGRUID,EVT,TNAKEY,IS_DST,TMZN_HALF,TMZN_HOUR,TMZN_NEGTV,USRUDTBYDEV,HINT)
SELECT SRVDT,DEVDT,DEVUID,PKTDEVID,DEVLGIDX,USRID,USRGRUID,EVT,TNAKEY,IS_DST,TMZN_HALF,TMZN_HOUR,TMZN_NEGTV,USRUDTBYDEV,HINT
FROM [dbo].[T_LG202307]
WHERE SRVDT LIKE '%2023-08-01%' AND USRID <> '';