WITH nik_list AS (SELECT DISTINCT NIK FROM tblattendance)
SELECT
    TA.NIK,
    TK.NAMA,
    TD.[Nama Departemen],
    
    sts01 as [01],sts02 as [02],sts03 as [03],sts04 as [04],sts05 as [05],sts06 as [06],sts07 as [07],sts08 as [08],sts09 as [09],
	sts10 as [10],sts11 as [11],sts12 as [12],sts13 as [13],sts14 as [14],sts15 as [15],sts16 as [16],sts17 as [17],sts18 as [18],
	sts19 as [19],sts20 as [20],sts21 as [21],sts22 as [22],sts23 as [23],sts24 as [24],sts25 as [25],sts26 as [26],sts27 as [27],
	sts28 as [28],sts29 as [29],sts30 as [30],sts31 as [31],
    SUM(
		   CASE WHEN Sts01 = 'H' THEN 1 ELSE 0 END + CASE WHEN Sts02 = 'H' THEN 1 ELSE 0 END + CASE WHEN Sts03 = 'H' THEN 1 ELSE 0 END + CASE WHEN Sts04 = 'H' THEN 1 ELSE 0 END +
           CASE WHEN Sts05 = 'H' THEN 1 ELSE 0 END + CASE WHEN Sts06 = 'H' THEN 1 ELSE 0 END + CASE WHEN Sts07 = 'H' THEN 1 ELSE 0 END + CASE WHEN Sts08 = 'H' THEN 1 ELSE 0 END +
		   CASE WHEN Sts09 = 'H' THEN 1 ELSE 0 END + CASE WHEN Sts10 = 'H' THEN 1 ELSE 0 END + CASE WHEN Sts11 = 'H' THEN 1 ELSE 0 END + CASE WHEN Sts12 = 'H' THEN 1 ELSE 0 END +
		   CASE WHEN Sts13 = 'H' THEN 1 ELSE 0 END + CASE WHEN Sts14 = 'H' THEN 1 ELSE 0 END + CASE WHEN Sts15 = 'H' THEN 1 ELSE 0 END + CASE WHEN Sts16 = 'H' THEN 1 ELSE 0 END +
		   CASE WHEN Sts17 = 'H' THEN 1 ELSE 0 END + CASE WHEN Sts18 = 'H' THEN 1 ELSE 0 END + CASE WHEN Sts19 = 'H' THEN 1 ELSE 0 END + CASE WHEN Sts20 = 'H' THEN 1 ELSE 0 END +
		   CASE WHEN Sts21 = 'H' THEN 1 ELSE 0 END + CASE WHEN Sts22 = 'H' THEN 1 ELSE 0 END + CASE WHEN Sts23 = 'H' THEN 1 ELSE 0 END + CASE WHEN Sts24 = 'H' THEN 1 ELSE 0 END +
		   CASE WHEN Sts25 = 'H' THEN 1 ELSE 0 END + CASE WHEN Sts26 = 'H' THEN 1 ELSE 0 END + CASE WHEN Sts27 = 'H' THEN 1 ELSE 0 END + CASE WHEN Sts28 = 'H' THEN 1 ELSE 0 END +
		   CASE WHEN Sts29 = 'H' THEN 1 ELSE 0 END + CASE WHEN Sts30 = 'H' THEN 1 ELSE 0 END + CASE WHEN Sts31 = 'H' THEN 1 ELSE 0 END
    ) AS [HADIR (H)],
	SUM(
		   CASE WHEN Sts01 = 'A' THEN 1 ELSE 0 END + CASE WHEN Sts02 = 'A' THEN 1 ELSE 0 END + CASE WHEN Sts03 = 'A' THEN 1 ELSE 0 END + CASE WHEN Sts04 = 'A' THEN 1 ELSE 0 END +
           CASE WHEN Sts05 = 'A' THEN 1 ELSE 0 END + CASE WHEN Sts06 = 'A' THEN 1 ELSE 0 END + CASE WHEN Sts07 = 'A' THEN 1 ELSE 0 END + CASE WHEN Sts08 = 'A' THEN 1 ELSE 0 END +
		   CASE WHEN Sts09 = 'A' THEN 1 ELSE 0 END + CASE WHEN Sts10 = 'A' THEN 1 ELSE 0 END + CASE WHEN Sts11 = 'A' THEN 1 ELSE 0 END + CASE WHEN Sts12 = 'A' THEN 1 ELSE 0 END +
		   CASE WHEN Sts13 = 'A' THEN 1 ELSE 0 END + CASE WHEN Sts14 = 'A' THEN 1 ELSE 0 END + CASE WHEN Sts15 = 'A' THEN 1 ELSE 0 END + CASE WHEN Sts16 = 'A' THEN 1 ELSE 0 END +
		   CASE WHEN Sts17 = 'A' THEN 1 ELSE 0 END + CASE WHEN Sts18 = 'A' THEN 1 ELSE 0 END + CASE WHEN Sts19 = 'A' THEN 1 ELSE 0 END + CASE WHEN Sts20 = 'A' THEN 1 ELSE 0 END +
		   CASE WHEN Sts21 = 'A' THEN 1 ELSE 0 END + CASE WHEN Sts22 = 'A' THEN 1 ELSE 0 END + CASE WHEN Sts23 = 'A' THEN 1 ELSE 0 END + CASE WHEN Sts24 = 'A' THEN 1 ELSE 0 END +
		   CASE WHEN Sts25 = 'A' THEN 1 ELSE 0 END + CASE WHEN Sts26 = 'A' THEN 1 ELSE 0 END + CASE WHEN Sts27 = 'A' THEN 1 ELSE 0 END + CASE WHEN Sts28 = 'A' THEN 1 ELSE 0 END +
		   CASE WHEN Sts29 = 'A' THEN 1 ELSE 0 END + CASE WHEN Sts30 = 'A' THEN 1 ELSE 0 END + CASE WHEN Sts31 = 'A' THEN 1 ELSE 0 END
    ) AS [ALFA (A)],
	SUM(
		   CASE WHEN Sts01 = 'I' THEN 1 ELSE 0 END + CASE WHEN Sts02 = 'I' THEN 1 ELSE 0 END + CASE WHEN Sts03 = 'I' THEN 1 ELSE 0 END + CASE WHEN Sts04 = 'I' THEN 1 ELSE 0 END +
           CASE WHEN Sts05 = 'I' THEN 1 ELSE 0 END + CASE WHEN Sts06 = 'I' THEN 1 ELSE 0 END + CASE WHEN Sts07 = 'I' THEN 1 ELSE 0 END + CASE WHEN Sts08 = 'I' THEN 1 ELSE 0 END +
		   CASE WHEN Sts09 = 'I' THEN 1 ELSE 0 END + CASE WHEN Sts10 = 'I' THEN 1 ELSE 0 END + CASE WHEN Sts11 = 'I' THEN 1 ELSE 0 END + CASE WHEN Sts12 = 'I' THEN 1 ELSE 0 END +
		   CASE WHEN Sts13 = 'I' THEN 1 ELSE 0 END + CASE WHEN Sts14 = 'I' THEN 1 ELSE 0 END + CASE WHEN Sts15 = 'I' THEN 1 ELSE 0 END + CASE WHEN Sts16 = 'I' THEN 1 ELSE 0 END +
		   CASE WHEN Sts17 = 'I' THEN 1 ELSE 0 END + CASE WHEN Sts18 = 'I' THEN 1 ELSE 0 END + CASE WHEN Sts19 = 'I' THEN 1 ELSE 0 END + CASE WHEN Sts20 = 'I' THEN 1 ELSE 0 END +
		   CASE WHEN Sts21 = 'I' THEN 1 ELSE 0 END + CASE WHEN Sts22 = 'I' THEN 1 ELSE 0 END + CASE WHEN Sts23 = 'I' THEN 1 ELSE 0 END + CASE WHEN Sts24 = 'I' THEN 1 ELSE 0 END +
		   CASE WHEN Sts25 = 'I' THEN 1 ELSE 0 END + CASE WHEN Sts26 = 'I' THEN 1 ELSE 0 END + CASE WHEN Sts27 = 'I' THEN 1 ELSE 0 END + CASE WHEN Sts28 = 'I' THEN 1 ELSE 0 END +
		   CASE WHEN Sts29 = 'I' THEN 1 ELSE 0 END + CASE WHEN Sts30 = 'I' THEN 1 ELSE 0 END + CASE WHEN Sts31 = 'I' THEN 1 ELSE 0 END
    ) AS [IZIN (I)],
	SUM(
		   CASE WHEN Sts01 = 'S' THEN 1 ELSE 0 END + CASE WHEN Sts02 = 'S' THEN 1 ELSE 0 END + CASE WHEN Sts03 = 'S' THEN 1 ELSE 0 END + CASE WHEN Sts04 = 'S' THEN 1 ELSE 0 END +
           CASE WHEN Sts05 = 'S' THEN 1 ELSE 0 END + CASE WHEN Sts06 = 'S' THEN 1 ELSE 0 END + CASE WHEN Sts07 = 'S' THEN 1 ELSE 0 END + CASE WHEN Sts08 = 'S' THEN 1 ELSE 0 END +
		   CASE WHEN Sts09 = 'S' THEN 1 ELSE 0 END + CASE WHEN Sts10 = 'S' THEN 1 ELSE 0 END + CASE WHEN Sts11 = 'S' THEN 1 ELSE 0 END + CASE WHEN Sts12 = 'S' THEN 1 ELSE 0 END +
		   CASE WHEN Sts13 = 'S' THEN 1 ELSE 0 END + CASE WHEN Sts14 = 'S' THEN 1 ELSE 0 END + CASE WHEN Sts15 = 'S' THEN 1 ELSE 0 END + CASE WHEN Sts16 = 'S' THEN 1 ELSE 0 END +
		   CASE WHEN Sts17 = 'S' THEN 1 ELSE 0 END + CASE WHEN Sts18 = 'S' THEN 1 ELSE 0 END + CASE WHEN Sts19 = 'S' THEN 1 ELSE 0 END + CASE WHEN Sts20 = 'S' THEN 1 ELSE 0 END +
		   CASE WHEN Sts21 = 'S' THEN 1 ELSE 0 END + CASE WHEN Sts22 = 'S' THEN 1 ELSE 0 END + CASE WHEN Sts23 = 'S' THEN 1 ELSE 0 END + CASE WHEN Sts24 = 'S' THEN 1 ELSE 0 END +
		   CASE WHEN Sts25 = 'S' THEN 1 ELSE 0 END + CASE WHEN Sts26 = 'S' THEN 1 ELSE 0 END + CASE WHEN Sts27 = 'S' THEN 1 ELSE 0 END + CASE WHEN Sts28 = 'S' THEN 1 ELSE 0 END +
		   CASE WHEN Sts29 = 'S' THEN 1 ELSE 0 END + CASE WHEN Sts30 = 'S' THEN 1 ELSE 0 END + CASE WHEN Sts31 = 'S' THEN 1 ELSE 0 END
    ) AS [SAKIT (S)],
	SUM(
		   CASE WHEN Sts01 = 'D' THEN 1 ELSE 0 END + CASE WHEN Sts02 = 'D' THEN 1 ELSE 0 END + CASE WHEN Sts03 = 'D' THEN 1 ELSE 0 END + CASE WHEN Sts04 = 'D' THEN 1 ELSE 0 END +
           CASE WHEN Sts05 = 'D' THEN 1 ELSE 0 END + CASE WHEN Sts06 = 'D' THEN 1 ELSE 0 END + CASE WHEN Sts07 = 'D' THEN 1 ELSE 0 END + CASE WHEN Sts08 = 'D' THEN 1 ELSE 0 END +
		   CASE WHEN Sts09 = 'D' THEN 1 ELSE 0 END + CASE WHEN Sts10 = 'D' THEN 1 ELSE 0 END + CASE WHEN Sts11 = 'D' THEN 1 ELSE 0 END + CASE WHEN Sts12 = 'D' THEN 1 ELSE 0 END +
		   CASE WHEN Sts13 = 'D' THEN 1 ELSE 0 END + CASE WHEN Sts14 = 'D' THEN 1 ELSE 0 END + CASE WHEN Sts15 = 'D' THEN 1 ELSE 0 END + CASE WHEN Sts16 = 'D' THEN 1 ELSE 0 END +
		   CASE WHEN Sts17 = 'D' THEN 1 ELSE 0 END + CASE WHEN Sts18 = 'D' THEN 1 ELSE 0 END + CASE WHEN Sts19 = 'D' THEN 1 ELSE 0 END + CASE WHEN Sts20 = 'D' THEN 1 ELSE 0 END +
		   CASE WHEN Sts21 = 'D' THEN 1 ELSE 0 END + CASE WHEN Sts22 = 'D' THEN 1 ELSE 0 END + CASE WHEN Sts23 = 'D' THEN 1 ELSE 0 END + CASE WHEN Sts24 = 'D' THEN 1 ELSE 0 END +
		   CASE WHEN Sts25 = 'D' THEN 1 ELSE 0 END + CASE WHEN Sts26 = 'D' THEN 1 ELSE 0 END + CASE WHEN Sts27 = 'D' THEN 1 ELSE 0 END + CASE WHEN Sts28 = 'D' THEN 1 ELSE 0 END +
		   CASE WHEN Sts29 = 'D' THEN 1 ELSE 0 END + CASE WHEN Sts30 = 'D' THEN 1 ELSE 0 END + CASE WHEN Sts31 = 'D' THEN 1 ELSE 0 END
    ) AS [SAKIT SURAT DOKTER (D)],
	SUM(
		   CASE WHEN Sts01 = 'C' THEN 1 ELSE 0 END + CASE WHEN Sts02 = 'C' THEN 1 ELSE 0 END + CASE WHEN Sts03 = 'C' THEN 1 ELSE 0 END + CASE WHEN Sts04 = 'C' THEN 1 ELSE 0 END +
           CASE WHEN Sts05 = 'C' THEN 1 ELSE 0 END + CASE WHEN Sts06 = 'C' THEN 1 ELSE 0 END + CASE WHEN Sts07 = 'C' THEN 1 ELSE 0 END + CASE WHEN Sts08 = 'C' THEN 1 ELSE 0 END +
		   CASE WHEN Sts09 = 'C' THEN 1 ELSE 0 END + CASE WHEN Sts10 = 'C' THEN 1 ELSE 0 END + CASE WHEN Sts11 = 'C' THEN 1 ELSE 0 END + CASE WHEN Sts12 = 'C' THEN 1 ELSE 0 END +
		   CASE WHEN Sts13 = 'C' THEN 1 ELSE 0 END + CASE WHEN Sts14 = 'C' THEN 1 ELSE 0 END + CASE WHEN Sts15 = 'C' THEN 1 ELSE 0 END + CASE WHEN Sts16 = 'C' THEN 1 ELSE 0 END +
		   CASE WHEN Sts17 = 'C' THEN 1 ELSE 0 END + CASE WHEN Sts18 = 'C' THEN 1 ELSE 0 END + CASE WHEN Sts19 = 'C' THEN 1 ELSE 0 END + CASE WHEN Sts20 = 'C' THEN 1 ELSE 0 END +
		   CASE WHEN Sts21 = 'C' THEN 1 ELSE 0 END + CASE WHEN Sts22 = 'C' THEN 1 ELSE 0 END + CASE WHEN Sts23 = 'C' THEN 1 ELSE 0 END + CASE WHEN Sts24 = 'C' THEN 1 ELSE 0 END +
		   CASE WHEN Sts25 = 'C' THEN 1 ELSE 0 END + CASE WHEN Sts26 = 'C' THEN 1 ELSE 0 END + CASE WHEN Sts27 = 'C' THEN 1 ELSE 0 END + CASE WHEN Sts28 = 'C' THEN 1 ELSE 0 END +
		   CASE WHEN Sts29 = 'C' THEN 1 ELSE 0 END + CASE WHEN Sts30 = 'C' THEN 1 ELSE 0 END + CASE WHEN Sts31 = 'C' THEN 1 ELSE 0 END
    ) AS [CUTI TAHUNAN (C)],
	SUM(
		   CASE WHEN Sts01 = '' THEN 1 ELSE 0 END + CASE WHEN Sts02 = '' THEN 1 ELSE 0 END + CASE WHEN Sts03 = '' THEN 1 ELSE 0 END + CASE WHEN Sts04 = '' THEN 1 ELSE 0 END +
           CASE WHEN Sts05 = '' THEN 1 ELSE 0 END + CASE WHEN Sts06 = '' THEN 1 ELSE 0 END + CASE WHEN Sts07 = '' THEN 1 ELSE 0 END + CASE WHEN Sts08 = '' THEN 1 ELSE 0 END +
		   CASE WHEN Sts09 = '' THEN 1 ELSE 0 END + CASE WHEN Sts10 = '' THEN 1 ELSE 0 END + CASE WHEN Sts11 = '' THEN 1 ELSE 0 END + CASE WHEN Sts12 = '' THEN 1 ELSE 0 END +
		   CASE WHEN Sts13 = '' THEN 1 ELSE 0 END + CASE WHEN Sts14 = '' THEN 1 ELSE 0 END + CASE WHEN Sts15 = '' THEN 1 ELSE 0 END + CASE WHEN Sts16 = '' THEN 1 ELSE 0 END +
		   CASE WHEN Sts17 = '' THEN 1 ELSE 0 END + CASE WHEN Sts18 = '' THEN 1 ELSE 0 END + CASE WHEN Sts19 = '' THEN 1 ELSE 0 END + CASE WHEN Sts20 = '' THEN 1 ELSE 0 END +
		   CASE WHEN Sts21 = '' THEN 1 ELSE 0 END + CASE WHEN Sts22 = '' THEN 1 ELSE 0 END + CASE WHEN Sts23 = '' THEN 1 ELSE 0 END + CASE WHEN Sts24 = '' THEN 1 ELSE 0 END +
		   CASE WHEN Sts25 = '' THEN 1 ELSE 0 END + CASE WHEN Sts26 = '' THEN 1 ELSE 0 END + CASE WHEN Sts27 = '' THEN 1 ELSE 0 END + CASE WHEN Sts28 = '' THEN 1 ELSE 0 END +
		   CASE WHEN Sts29 = '' THEN 1 ELSE 0 END + CASE WHEN Sts30 = '' THEN 1 ELSE 0 END + CASE WHEN Sts31 = '' THEN 1 ELSE 0 END
    ) AS [KOSONG ATAU ALFA],
	SLP.Absen,TK.[Tgl. Kerja Lama],TK.[Resign Date]
    --TK.[Resign Date],
    --CASE WHEN DATEDIFF(MONTH, TK.[Tgl. Kerja Lama], GETDATE()) >= 12 THEN 12 ELSE 0 END AS [Cuti Tahunan],
    --DATEDIFF(YEAR, TK.[Tgl. Kerja Lama], GETDATE()) AS [PERIODE KERJA PERTAHUN]
FROM tblattendance AS TA
INNER JOIN tblkaryawan AS TK ON TA.nik = TK.nik
INNER JOIN tblDept AS TD ON TK.[Kode Dept] = TD.[Kode Dept]
inner join tblSlipGaji as SLP ON TA.NIK = SLP.NIK
WHERE TA.NIK IN (SELECT NIK FROM nik_list) AND TA.Tahun = '2024' AND TK.Resign = 'N' and TA.BULAN = '02'--AND TA.Bulan IN ('01','02','03','05','06','07','08','09','10')
		AND SLP.[H Kerja] = 21 AND SLP.TAHUN = 2024 AND SLP.BULAN = 2
GROUP BY TA.NIK, TK.NAMA, TK.[Resign Date], TD.[Nama Departemen], TK.[Tgl. Kerja Lama],
sts01,sts02,sts03,sts04,sts05,sts06,sts07,sts08,sts09,sts10,sts11,sts12,sts13,sts14,sts15,sts16,sts17,sts18,sts19,sts20,sts21,sts22,sts23,sts24,sts25,sts26,sts27,sts28,sts29,sts30,sts31,Absen
ORDER BY TA.NIK;