SELECT 
    tahun,
    LTRIM(RTRIM(TA.nik)) AS nik,
    LTRIM(RTRIM(TK.NAMA)) AS nama,
    LTRIM(RTRIM(TD.[Nama Departemen])) AS nama_departemen,
    LTRIM(RTRIM(TB.[Nama Bagian])) AS nama_bagian,
    LTRIM(RTRIM(TJ.Jabatan)) AS jabatan,
    LTRIM(RTRIM(TK.[Tgl. Kerja Lama])) AS tgl_kerja_lama,
    LTRIM(RTRIM(TK.[Resign Date])) AS resign_date,
	SUM(
        (CASE WHEN TA.BULAN = 6 AND Sts01 = 'A' THEN 1 ELSE 0 END) + (CASE WHEN TA.BULAN = 6 AND Sts02 = 'A' THEN 1 ELSE 0 END) + (CASE WHEN TA.BULAN = 6 AND Sts03 = 'A' THEN 1 ELSE 0 END) +
        (CASE WHEN TA.BULAN = 6 AND Sts04 = 'A' THEN 1 ELSE 0 END) + (CASE WHEN TA.BULAN = 6 AND Sts05 = 'A' THEN 1 ELSE 0 END) + (CASE WHEN TA.BULAN = 6 AND Sts06 = 'A' THEN 1 ELSE 0 END) +
        (CASE WHEN TA.BULAN = 6 AND Sts07 = 'A' THEN 1 ELSE 0 END) + (CASE WHEN TA.BULAN = 6 AND Sts08 = 'A' THEN 1 ELSE 0 END) + (CASE WHEN TA.BULAN = 6 AND Sts09 = 'A' THEN 1 ELSE 0 END) +
        (CASE WHEN TA.BULAN = 6 AND Sts10 = 'A' THEN 1 ELSE 0 END) + (CASE WHEN TA.BULAN = 6 AND Sts11 = 'A' THEN 1 ELSE 0 END) + (CASE WHEN TA.BULAN = 6 AND Sts12 = 'A' THEN 1 ELSE 0 END) +
        (CASE WHEN TA.BULAN = 6 AND Sts13 = 'A' THEN 1 ELSE 0 END) + (CASE WHEN TA.BULAN = 6 AND Sts14 = 'A' THEN 1 ELSE 0 END) + (CASE WHEN TA.BULAN = 6 AND Sts15 = 'A' THEN 1 ELSE 0 END) +
        (CASE WHEN TA.BULAN = 6 AND Sts16 = 'A' THEN 1 ELSE 0 END) + (CASE WHEN TA.BULAN = 6 AND Sts17 = 'A' THEN 1 ELSE 0 END) + (CASE WHEN TA.BULAN = 6 AND Sts18 = 'A' THEN 1 ELSE 0 END) +
        (CASE WHEN TA.BULAN = 6 AND Sts19 = 'A' THEN 1 ELSE 0 END) + (CASE WHEN TA.BULAN = 6 AND Sts20 = 'A' THEN 1 ELSE 0 END) + (CASE WHEN TA.BULAN = 6 AND Sts21 = 'A' THEN 1 ELSE 0 END) +
        (CASE WHEN TA.BULAN = 6 AND Sts22 = 'A' THEN 1 ELSE 0 END) + (CASE WHEN TA.BULAN = 6 AND Sts23 = 'A' THEN 1 ELSE 0 END) + (CASE WHEN TA.BULAN = 6 AND Sts24 = 'A' THEN 1 ELSE 0 END) +
        (CASE WHEN TA.BULAN = 6 AND Sts25 = 'A' THEN 1 ELSE 0 END) + (CASE WHEN TA.BULAN = 6 AND Sts26 = 'A' THEN 1 ELSE 0 END) + (CASE WHEN TA.BULAN = 6 AND Sts27 = 'A' THEN 1 ELSE 0 END) +
        (CASE WHEN TA.BULAN = 6 AND Sts28 = 'A' THEN 1 ELSE 0 END) + (CASE WHEN TA.BULAN = 6 AND Sts29 = 'A' THEN 1 ELSE 0 END) + (CASE WHEN TA.BULAN = 6 AND Sts30 = 'A' THEN 1 ELSE 0 END) +
        (CASE WHEN TA.BULAN = 6 AND Sts31 = 'A' THEN 1 ELSE 0 END)
    ) AS ALFA,
	SUM(
        (CASE WHEN TA.BULAN = 6 AND Sts01 = 'I' THEN 1 ELSE 0 END) + (CASE WHEN TA.BULAN = 6 AND Sts02 = 'I' THEN 1 ELSE 0 END) + (CASE WHEN TA.BULAN = 6 AND Sts03 = 'I' THEN 1 ELSE 0 END) +
        (CASE WHEN TA.BULAN = 6 AND Sts04 = 'I' THEN 1 ELSE 0 END) + (CASE WHEN TA.BULAN = 6 AND Sts05 = 'I' THEN 1 ELSE 0 END) + (CASE WHEN TA.BULAN = 6 AND Sts06 = 'I' THEN 1 ELSE 0 END) +
        (CASE WHEN TA.BULAN = 6 AND Sts07 = 'I' THEN 1 ELSE 0 END) + (CASE WHEN TA.BULAN = 6 AND Sts08 = 'I' THEN 1 ELSE 0 END) + (CASE WHEN TA.BULAN = 6 AND Sts09 = 'I' THEN 1 ELSE 0 END) +
        (CASE WHEN TA.BULAN = 6 AND Sts10 = 'I' THEN 1 ELSE 0 END) + (CASE WHEN TA.BULAN = 6 AND Sts11 = 'I' THEN 1 ELSE 0 END) + (CASE WHEN TA.BULAN = 6 AND Sts12 = 'I' THEN 1 ELSE 0 END) +
        (CASE WHEN TA.BULAN = 6 AND Sts13 = 'I' THEN 1 ELSE 0 END) + (CASE WHEN TA.BULAN = 6 AND Sts14 = 'I' THEN 1 ELSE 0 END) + (CASE WHEN TA.BULAN = 6 AND Sts15 = 'I' THEN 1 ELSE 0 END) +
        (CASE WHEN TA.BULAN = 6 AND Sts16 = 'I' THEN 1 ELSE 0 END) + (CASE WHEN TA.BULAN = 6 AND Sts17 = 'I' THEN 1 ELSE 0 END) + (CASE WHEN TA.BULAN = 6 AND Sts18 = 'I' THEN 1 ELSE 0 END) +
        (CASE WHEN TA.BULAN = 6 AND Sts19 = 'I' THEN 1 ELSE 0 END) + (CASE WHEN TA.BULAN = 6 AND Sts20 = 'I' THEN 1 ELSE 0 END) + (CASE WHEN TA.BULAN = 6 AND Sts21 = 'I' THEN 1 ELSE 0 END) +
        (CASE WHEN TA.BULAN = 6 AND Sts22 = 'I' THEN 1 ELSE 0 END) + (CASE WHEN TA.BULAN = 6 AND Sts23 = 'I' THEN 1 ELSE 0 END) + (CASE WHEN TA.BULAN = 6 AND Sts24 = 'I' THEN 1 ELSE 0 END) +
        (CASE WHEN TA.BULAN = 6 AND Sts25 = 'I' THEN 1 ELSE 0 END) + (CASE WHEN TA.BULAN = 6 AND Sts26 = 'I' THEN 1 ELSE 0 END) + (CASE WHEN TA.BULAN = 6 AND Sts27 = 'I' THEN 1 ELSE 0 END) +
        (CASE WHEN TA.BULAN = 6 AND Sts28 = 'I' THEN 1 ELSE 0 END) + (CASE WHEN TA.BULAN = 6 AND Sts29 = 'I' THEN 1 ELSE 0 END) + (CASE WHEN TA.BULAN = 6 AND Sts30 = 'I' THEN 1 ELSE 0 END) +
        (CASE WHEN TA.BULAN = 6 AND Sts31 = 'I' THEN 1 ELSE 0 END)
    ) AS IZIN,
	SUM(
        (CASE WHEN TA.BULAN = 6 AND Sts01 = 'C' THEN 1 ELSE 0 END) + (CASE WHEN TA.BULAN = 6 AND Sts02 = 'C' THEN 1 ELSE 0 END) + (CASE WHEN TA.BULAN = 6 AND Sts03 = 'C' THEN 1 ELSE 0 END) +
        (CASE WHEN TA.BULAN = 6 AND Sts04 = 'C' THEN 1 ELSE 0 END) + (CASE WHEN TA.BULAN = 6 AND Sts05 = 'C' THEN 1 ELSE 0 END) + (CASE WHEN TA.BULAN = 6 AND Sts06 = 'C' THEN 1 ELSE 0 END) +
        (CASE WHEN TA.BULAN = 6 AND Sts07 = 'C' THEN 1 ELSE 0 END) + (CASE WHEN TA.BULAN = 6 AND Sts08 = 'C' THEN 1 ELSE 0 END) + (CASE WHEN TA.BULAN = 6 AND Sts09 = 'C' THEN 1 ELSE 0 END) +
        (CASE WHEN TA.BULAN = 6 AND Sts10 = 'C' THEN 1 ELSE 0 END) + (CASE WHEN TA.BULAN = 6 AND Sts11 = 'C' THEN 1 ELSE 0 END) + (CASE WHEN TA.BULAN = 6 AND Sts12 = 'C' THEN 1 ELSE 0 END) +
        (CASE WHEN TA.BULAN = 6 AND Sts13 = 'C' THEN 1 ELSE 0 END) + (CASE WHEN TA.BULAN = 6 AND Sts14 = 'C' THEN 1 ELSE 0 END) + (CASE WHEN TA.BULAN = 6 AND Sts15 = 'C' THEN 1 ELSE 0 END) +
        (CASE WHEN TA.BULAN = 6 AND Sts16 = 'C' THEN 1 ELSE 0 END) + (CASE WHEN TA.BULAN = 6 AND Sts17 = 'C' THEN 1 ELSE 0 END) + (CASE WHEN TA.BULAN = 6 AND Sts18 = 'C' THEN 1 ELSE 0 END) +
        (CASE WHEN TA.BULAN = 6 AND Sts19 = 'C' THEN 1 ELSE 0 END) + (CASE WHEN TA.BULAN = 6 AND Sts20 = 'C' THEN 1 ELSE 0 END) + (CASE WHEN TA.BULAN = 6 AND Sts21 = 'C' THEN 1 ELSE 0 END) +
        (CASE WHEN TA.BULAN = 6 AND Sts22 = 'C' THEN 1 ELSE 0 END) + (CASE WHEN TA.BULAN = 6 AND Sts23 = 'C' THEN 1 ELSE 0 END) + (CASE WHEN TA.BULAN = 6 AND Sts24 = 'C' THEN 1 ELSE 0 END) +
        (CASE WHEN TA.BULAN = 6 AND Sts25 = 'C' THEN 1 ELSE 0 END) + (CASE WHEN TA.BULAN = 6 AND Sts26 = 'C' THEN 1 ELSE 0 END) + (CASE WHEN TA.BULAN = 6 AND Sts27 = 'C' THEN 1 ELSE 0 END) +
        (CASE WHEN TA.BULAN = 6 AND Sts28 = 'C' THEN 1 ELSE 0 END) + (CASE WHEN TA.BULAN = 6 AND Sts29 = 'C' THEN 1 ELSE 0 END) + (CASE WHEN TA.BULAN = 6 AND Sts30 = 'C' THEN 1 ELSE 0 END) +
        (CASE WHEN TA.BULAN = 6 AND Sts31 = 'C' THEN 1 ELSE 0 END)
    ) AS CUTI_TAHUNAN,
	SUM(
        (CASE WHEN TA.BULAN = 6 AND Sts01 IN ('Y','V','W','X') THEN 1 ELSE 0 END) + (CASE WHEN TA.BULAN = 6 AND Sts02 IN ('Y','V','W','X') THEN 1 ELSE 0 END) + (CASE WHEN TA.BULAN = 6 AND Sts03 IN ('Y','V','W','X') THEN 1 ELSE 0 END) +
        (CASE WHEN TA.BULAN = 6 AND Sts04 IN ('Y','V','W','X') THEN 1 ELSE 0 END) + (CASE WHEN TA.BULAN = 6 AND Sts05 IN ('Y','V','W','X') THEN 1 ELSE 0 END) + (CASE WHEN TA.BULAN = 6 AND Sts06 IN ('Y','V','W','X') THEN 1 ELSE 0 END) +
        (CASE WHEN TA.BULAN = 6 AND Sts07 IN ('Y','V','W','X') THEN 1 ELSE 0 END) + (CASE WHEN TA.BULAN = 6 AND Sts08 IN ('Y','V','W','X') THEN 1 ELSE 0 END) + (CASE WHEN TA.BULAN = 6 AND Sts09 IN ('Y','V','W','X') THEN 1 ELSE 0 END) +
        (CASE WHEN TA.BULAN = 6 AND Sts10 IN ('Y','V','W','X') THEN 1 ELSE 0 END) + (CASE WHEN TA.BULAN = 6 AND Sts11 IN ('Y','V','W','X') THEN 1 ELSE 0 END) + (CASE WHEN TA.BULAN = 6 AND Sts12 IN ('Y','V','W','X') THEN 1 ELSE 0 END) +
        (CASE WHEN TA.BULAN = 6 AND Sts13 IN ('Y','V','W','X') THEN 1 ELSE 0 END) + (CASE WHEN TA.BULAN = 6 AND Sts14 IN ('Y','V','W','X') THEN 1 ELSE 0 END) + (CASE WHEN TA.BULAN = 6 AND Sts15 IN ('Y','V','W','X') THEN 1 ELSE 0 END) +
        (CASE WHEN TA.BULAN = 6 AND Sts16 IN ('Y','V','W','X') THEN 1 ELSE 0 END) + (CASE WHEN TA.BULAN = 6 AND Sts17 IN ('Y','V','W','X') THEN 1 ELSE 0 END) + (CASE WHEN TA.BULAN = 6 AND Sts18 IN ('Y','V','W','X') THEN 1 ELSE 0 END) +
        (CASE WHEN TA.BULAN = 6 AND Sts19 IN ('Y','V','W','X') THEN 1 ELSE 0 END) + (CASE WHEN TA.BULAN = 6 AND Sts20 IN ('Y','V','W','X') THEN 1 ELSE 0 END) + (CASE WHEN TA.BULAN = 6 AND Sts21 IN ('Y','V','W','X') THEN 1 ELSE 0 END) +
        (CASE WHEN TA.BULAN = 6 AND Sts22 IN ('Y','V','W','X') THEN 1 ELSE 0 END) + (CASE WHEN TA.BULAN = 6 AND Sts23 IN ('Y','V','W','X') THEN 1 ELSE 0 END) + (CASE WHEN TA.BULAN = 6 AND Sts24 IN ('Y','V','W','X') THEN 1 ELSE 0 END) +
        (CASE WHEN TA.BULAN = 6 AND Sts25 IN ('Y','V','W','X') THEN 1 ELSE 0 END) + (CASE WHEN TA.BULAN = 6 AND Sts26 IN ('Y','V','W','X') THEN 1 ELSE 0 END) + (CASE WHEN TA.BULAN = 6 AND Sts27 IN ('Y','V','W','X') THEN 1 ELSE 0 END) +
        (CASE WHEN TA.BULAN = 6 AND Sts28 IN ('Y','V','W','X') THEN 1 ELSE 0 END) + (CASE WHEN TA.BULAN = 6 AND Sts29 IN ('Y','V','W','X') THEN 1 ELSE 0 END) + (CASE WHEN TA.BULAN = 6 AND Sts30 IN ('Y','V','W','X') THEN 1 ELSE 0 END) +
        (CASE WHEN TA.BULAN = 6 AND Sts31 IN ('Y','V','W','X') THEN 1 ELSE 0 END)
    ) AS CUTI_LAINNYA,
	SUM(
        (CASE WHEN TA.BULAN = 6 AND Sts01 = 'U' THEN 1 ELSE 0 END) + (CASE WHEN TA.BULAN = 6 AND Sts02 = 'U' THEN 1 ELSE 0 END) + (CASE WHEN TA.BULAN = 6 AND Sts03 = 'U' THEN 1 ELSE 0 END) +
        (CASE WHEN TA.BULAN = 6 AND Sts04 = 'U' THEN 1 ELSE 0 END) + (CASE WHEN TA.BULAN = 6 AND Sts05 = 'U' THEN 1 ELSE 0 END) + (CASE WHEN TA.BULAN = 6 AND Sts06 = 'U' THEN 1 ELSE 0 END) +
        (CASE WHEN TA.BULAN = 6 AND Sts07 = 'U' THEN 1 ELSE 0 END) + (CASE WHEN TA.BULAN = 6 AND Sts08 = 'U' THEN 1 ELSE 0 END) + (CASE WHEN TA.BULAN = 6 AND Sts09 = 'U' THEN 1 ELSE 0 END) +
        (CASE WHEN TA.BULAN = 6 AND Sts10 = 'U' THEN 1 ELSE 0 END) + (CASE WHEN TA.BULAN = 6 AND Sts11 = 'U' THEN 1 ELSE 0 END) + (CASE WHEN TA.BULAN = 6 AND Sts12 = 'U' THEN 1 ELSE 0 END) +
        (CASE WHEN TA.BULAN = 6 AND Sts13 = 'U' THEN 1 ELSE 0 END) + (CASE WHEN TA.BULAN = 6 AND Sts14 = 'U' THEN 1 ELSE 0 END) + (CASE WHEN TA.BULAN = 6 AND Sts15 = 'U' THEN 1 ELSE 0 END) +
        (CASE WHEN TA.BULAN = 6 AND Sts16 = 'U' THEN 1 ELSE 0 END) + (CASE WHEN TA.BULAN = 6 AND Sts17 = 'U' THEN 1 ELSE 0 END) + (CASE WHEN TA.BULAN = 6 AND Sts18 = 'U' THEN 1 ELSE 0 END) +
        (CASE WHEN TA.BULAN = 6 AND Sts19 = 'U' THEN 1 ELSE 0 END) + (CASE WHEN TA.BULAN = 6 AND Sts20 = 'U' THEN 1 ELSE 0 END) + (CASE WHEN TA.BULAN = 6 AND Sts21 = 'U' THEN 1 ELSE 0 END) +
        (CASE WHEN TA.BULAN = 6 AND Sts22 = 'U' THEN 1 ELSE 0 END) + (CASE WHEN TA.BULAN = 6 AND Sts23 = 'U' THEN 1 ELSE 0 END) + (CASE WHEN TA.BULAN = 6 AND Sts24 = 'U' THEN 1 ELSE 0 END) +
        (CASE WHEN TA.BULAN = 6 AND Sts25 = 'U' THEN 1 ELSE 0 END) + (CASE WHEN TA.BULAN = 6 AND Sts26 = 'U' THEN 1 ELSE 0 END) + (CASE WHEN TA.BULAN = 6 AND Sts27 = 'U' THEN 1 ELSE 0 END) +
        (CASE WHEN TA.BULAN = 6 AND Sts28 = 'U' THEN 1 ELSE 0 END) + (CASE WHEN TA.BULAN = 6 AND Sts29 = 'U' THEN 1 ELSE 0 END) + (CASE WHEN TA.BULAN = 6 AND Sts30 = 'U' THEN 1 ELSE 0 END) +
        (CASE WHEN TA.BULAN = 6 AND Sts31 = 'U' THEN 1 ELSE 0 END)
    ) AS CUTI_MELAHIRKAN,
	SUM(
        (CASE WHEN TA.BULAN = 6 AND Sts01 = 'S' THEN 1 ELSE 0 END) + (CASE WHEN TA.BULAN = 6 AND Sts02 = 'S' THEN 1 ELSE 0 END) + (CASE WHEN TA.BULAN = 6 AND Sts03 = 'S' THEN 1 ELSE 0 END) +
        (CASE WHEN TA.BULAN = 6 AND Sts04 = 'S' THEN 1 ELSE 0 END) + (CASE WHEN TA.BULAN = 6 AND Sts05 = 'S' THEN 1 ELSE 0 END) + (CASE WHEN TA.BULAN = 6 AND Sts06 = 'S' THEN 1 ELSE 0 END) +
        (CASE WHEN TA.BULAN = 6 AND Sts07 = 'S' THEN 1 ELSE 0 END) + (CASE WHEN TA.BULAN = 6 AND Sts08 = 'S' THEN 1 ELSE 0 END) + (CASE WHEN TA.BULAN = 6 AND Sts09 = 'S' THEN 1 ELSE 0 END) +
        (CASE WHEN TA.BULAN = 6 AND Sts10 = 'S' THEN 1 ELSE 0 END) + (CASE WHEN TA.BULAN = 6 AND Sts11 = 'S' THEN 1 ELSE 0 END) + (CASE WHEN TA.BULAN = 6 AND Sts12 = 'S' THEN 1 ELSE 0 END) +
        (CASE WHEN TA.BULAN = 6 AND Sts13 = 'S' THEN 1 ELSE 0 END) + (CASE WHEN TA.BULAN = 6 AND Sts14 = 'S' THEN 1 ELSE 0 END) + (CASE WHEN TA.BULAN = 6 AND Sts15 = 'S' THEN 1 ELSE 0 END) +
        (CASE WHEN TA.BULAN = 6 AND Sts16 = 'S' THEN 1 ELSE 0 END) + (CASE WHEN TA.BULAN = 6 AND Sts17 = 'S' THEN 1 ELSE 0 END) + (CASE WHEN TA.BULAN = 6 AND Sts18 = 'S' THEN 1 ELSE 0 END) +
        (CASE WHEN TA.BULAN = 6 AND Sts19 = 'S' THEN 1 ELSE 0 END) + (CASE WHEN TA.BULAN = 6 AND Sts20 = 'S' THEN 1 ELSE 0 END) + (CASE WHEN TA.BULAN = 6 AND Sts21 = 'S' THEN 1 ELSE 0 END) +
        (CASE WHEN TA.BULAN = 6 AND Sts22 = 'S' THEN 1 ELSE 0 END) + (CASE WHEN TA.BULAN = 6 AND Sts23 = 'S' THEN 1 ELSE 0 END) + (CASE WHEN TA.BULAN = 6 AND Sts24 = 'S' THEN 1 ELSE 0 END) +
        (CASE WHEN TA.BULAN = 6 AND Sts25 = 'S' THEN 1 ELSE 0 END) + (CASE WHEN TA.BULAN = 6 AND Sts26 = 'S' THEN 1 ELSE 0 END) + (CASE WHEN TA.BULAN = 6 AND Sts27 = 'S' THEN 1 ELSE 0 END) +
        (CASE WHEN TA.BULAN = 6 AND Sts28 = 'S' THEN 1 ELSE 0 END) + (CASE WHEN TA.BULAN = 6 AND Sts29 = 'S' THEN 1 ELSE 0 END) + (CASE WHEN TA.BULAN = 6 AND Sts30 = 'S' THEN 1 ELSE 0 END) +
        (CASE WHEN TA.BULAN = 6 AND Sts31 = 'S' THEN 1 ELSE 0 END)
    ) AS [SAKIT_TANPA SURAT DOKTER],
	SUM(
        (CASE WHEN TA.BULAN = 6 AND Sts01 = 'D' THEN 1 ELSE 0 END) + (CASE WHEN TA.BULAN = 6 AND Sts02 = 'D' THEN 1 ELSE 0 END) + (CASE WHEN TA.BULAN = 6 AND Sts03 = 'D' THEN 1 ELSE 0 END) +
        (CASE WHEN TA.BULAN = 6 AND Sts04 = 'D' THEN 1 ELSE 0 END) + (CASE WHEN TA.BULAN = 6 AND Sts05 = 'D' THEN 1 ELSE 0 END) + (CASE WHEN TA.BULAN = 6 AND Sts06 = 'D' THEN 1 ELSE 0 END) +
        (CASE WHEN TA.BULAN = 6 AND Sts07 = 'D' THEN 1 ELSE 0 END) + (CASE WHEN TA.BULAN = 6 AND Sts08 = 'D' THEN 1 ELSE 0 END) + (CASE WHEN TA.BULAN = 6 AND Sts09 = 'D' THEN 1 ELSE 0 END) +
        (CASE WHEN TA.BULAN = 6 AND Sts10 = 'D' THEN 1 ELSE 0 END) + (CASE WHEN TA.BULAN = 6 AND Sts11 = 'D' THEN 1 ELSE 0 END) + (CASE WHEN TA.BULAN = 6 AND Sts12 = 'D' THEN 1 ELSE 0 END) +
        (CASE WHEN TA.BULAN = 6 AND Sts13 = 'D' THEN 1 ELSE 0 END) + (CASE WHEN TA.BULAN = 6 AND Sts14 = 'D' THEN 1 ELSE 0 END) + (CASE WHEN TA.BULAN = 6 AND Sts15 = 'D' THEN 1 ELSE 0 END) +
        (CASE WHEN TA.BULAN = 6 AND Sts16 = 'D' THEN 1 ELSE 0 END) + (CASE WHEN TA.BULAN = 6 AND Sts17 = 'D' THEN 1 ELSE 0 END) + (CASE WHEN TA.BULAN = 6 AND Sts18 = 'D' THEN 1 ELSE 0 END) +
        (CASE WHEN TA.BULAN = 6 AND Sts19 = 'D' THEN 1 ELSE 0 END) + (CASE WHEN TA.BULAN = 6 AND Sts20 = 'D' THEN 1 ELSE 0 END) + (CASE WHEN TA.BULAN = 6 AND Sts21 = 'D' THEN 1 ELSE 0 END) +
        (CASE WHEN TA.BULAN = 6 AND Sts22 = 'D' THEN 1 ELSE 0 END) + (CASE WHEN TA.BULAN = 6 AND Sts23 = 'D' THEN 1 ELSE 0 END) + (CASE WHEN TA.BULAN = 6 AND Sts24 = 'D' THEN 1 ELSE 0 END) +
        (CASE WHEN TA.BULAN = 6 AND Sts25 = 'D' THEN 1 ELSE 0 END) + (CASE WHEN TA.BULAN = 6 AND Sts26 = 'D' THEN 1 ELSE 0 END) + (CASE WHEN TA.BULAN = 6 AND Sts27 = 'D' THEN 1 ELSE 0 END) +
        (CASE WHEN TA.BULAN = 6 AND Sts28 = 'D' THEN 1 ELSE 0 END) + (CASE WHEN TA.BULAN = 6 AND Sts29 = 'D' THEN 1 ELSE 0 END) + (CASE WHEN TA.BULAN = 6 AND Sts30 = 'D' THEN 1 ELSE 0 END) +
        (CASE WHEN TA.BULAN = 6 AND Sts31 = 'D' THEN 1 ELSE 0 END)
    ) AS [SAKIT_SURAT DOKTER]

FROM tblAttendance AS TA
INNER JOIN tblkaryawan AS TK WITH(NOLOCK) ON TA.nik=TK.nik
INNER JOIN tbldept AS TD WITH(NOLOCK) ON TD.[Kode Dept] = TK.[Kode Dept]
INNER JOIN TblJabatan AS TJ WITH(NOLOCK)  ON TJ.JabatanID = TK.[Kode Posisi]
INNER JOIN tblbagian AS TB WITH(NOLOCK) ON (TB.[Kode Dept] = TK.[Kode Dept] AND TB.[Kode Bagian] = TK.[Kode Bagian])
WHERE tahun = 2024
GROUP BY tahun, TA.nik, TK.NAMA, TD.[Nama Departemen],TB.[Nama Bagian],TJ.Jabatan,[Tgl. Kerja Lama],[Resign Date]
ORDER BY NIK,NAMA