DECLARE @TglSTART as date = '2023-05-01'

select A.tahun, A.bulan,
(SUM(CASE WHEN sts01 = 'H' THEN 6 ELSE 0 END) +
SUM(CASE WHEN sts02 = 'H' THEN 6 ELSE 0 END) +
SUM(CASE WHEN sts03 = 'H' THEN 6 ELSE 0 END) +
SUM(CASE WHEN sts04 = 'H' THEN 6 ELSE 0 END) +
SUM(CASE WHEN sts05 = 'H' THEN 6 ELSE 0 END) +
SUM(CASE WHEN sts06 = 'H' THEN 5 ELSE 0 END) +
SUM(CASE WHEN sts07 = 'H' THEN 6 ELSE 0 END) +
SUM(CASE WHEN sts08 = 'H' THEN 6 ELSE 0 END) +
SUM(CASE WHEN sts09 = 'H' THEN 6 ELSE 0 END) +
SUM(CASE WHEN sts10 = 'H' THEN 6 ELSE 0 END) +
SUM(CASE WHEN sts11 = 'H' THEN 6 ELSE 0 END) +
SUM(CASE WHEN sts12 = 'H' THEN 6 ELSE 0 END) +
SUM(CASE WHEN sts13 = 'H' THEN 5 ELSE 0 END) +
SUM(CASE WHEN sts14 = 'H' THEN 6 ELSE 0 END) +
SUM(CASE WHEN sts15 = 'H' THEN 6 ELSE 0 END) +
SUM(CASE WHEN sts16 = 'H' THEN 6 ELSE 0 END) +
SUM(CASE WHEN sts17 = 'H' THEN 6 ELSE 0 END) +
SUM(CASE WHEN sts18 = 'H' THEN 6 ELSE 0 END) +
SUM(CASE WHEN sts19 = 'H' THEN 6 ELSE 0 END) +
SUM(CASE WHEN sts20 = 'H' THEN 5 ELSE 0 END) +
SUM(CASE WHEN sts21 = 'H' THEN 6 ELSE 0 END) +
SUM(CASE WHEN sts22 = 'H' THEN 6 ELSE 0 END) +
SUM(CASE WHEN sts23 = 'H' THEN 6 ELSE 0 END) +
SUM(CASE WHEN sts24 = 'H' THEN 6 ELSE 0 END) +
SUM(CASE WHEN sts25 = 'H' THEN 6 ELSE 0 END) +
SUM(CASE WHEN sts26 = 'H' THEN 6 ELSE 0 END) +
SUM(CASE WHEN sts27 = 'H' THEN 5 ELSE 0 END) +
SUM(CASE WHEN sts28 = 'H' THEN 6 ELSE 0 END) +
SUM(CASE WHEN sts29 = 'H' THEN 6 ELSE 0 END) +
SUM(CASE WHEN sts30 = 'H' THEN 6 ELSE 0 END) +
SUM(CASE WHEN Sts31 = 'H' THEN 6 ELSE 0 END)) AS WORKTIME,
SUM(Lembur1+Lembur2+Lembur3+Lembur4) AS OVERTIME
FROM tblAttendance A
INNER JOIN tblSlipGaji G ON G.NIK = A.NIK
INNER JOIN tblKaryawan K ON K.NIK = A.NIK

where A.tahun = YEAR(@TglSTART) AND A.Bulan = MONTH(@TglSTART) AND
      G.Tahun = YEAR(@TglSTART) AND G.Bulan = MONTH(@TglSTART) AND
	  K.[Kode Dept] IN ('A','B','C','D','F','H','J','M','N','O','P','Q','R','E')
	  AND
	  K.[Kode Posisi] in ('G10','G46','G45','G30','G40')

GROUP BY A.Tahun , A.Bulan




